### ISSUE TITLE
Bug scipion Windows, printer mu dans la console fait planter le protocole

### ISSUE THREAD

**Issue by jplumail** [jplumail/scipion-fluo#4]
Dans le protocole `extract particles`, quand les particules ont des dims différentes, un message d'erreur est printé. Dans ce message d'erreur, un mu (caractère spécial) est affiché dans la console. Le protocole fail, python renvoie une erreur d'encoding. Il essaie de d'encoder le caractère \u03bc en cp1252 (encoding windows) mais n'y arrive pas. 

La question est pourquoi il essaie d'encoder en cp1252 ?? Problème avec `scipion-pyworkflow` sûrement, il faudrait voir dans le détail comment est lancé la commande. Je pense que l'encoding par défaut windows doit être le cp1252 donc python ouvre le fichier stdout.log dans cet encoding, ce qui doit faire planter car tous les print sont en utf8 ?

**Comment by jplumail** [comment]
j'ai réglé le pb en changeant mu en 'm' sur window

**Comment by azazellochg** [comment]
C'etait le protocole de relion ou xmipp - extract particles? Je peux verifier si on utilise UTF8

**Comment by jplumail** [comment]
@azazellochg merci c'est gentil ! Mais non c'est mon protocole import du module scipion-fluo qui réplique scipion-em sans la dépendance à Xmipp. Je travaille sur un fork de scipion-pyworkflow également... Donc difficile de répliquer mon bug !
